version: "3.8"

services:
  graphite:
    image: graphiteapp/graphite-statsd:latest
    container_name: graphite
    ports:
      - 2003:2003
      - 80:80

  grafana:
    image: grafana/grafana:7.0.1
    container_name: "grafana"
    volumes:
      - ../grafana_mnt:/var/lib/grafana
    ports:
      - 3000:3000

